//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Workshop.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class technology
    {
        public int techID { get; set; }
        public string name { get; set; }
        public bool status { get; set; }
        public bool isActive { get; set; }
    }
}
