//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Workshop.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class wssregistration
    {
        public int studentID { get; set; }
        public string name { get; set; }
        public string location { get; set; }
        public string technology { get; set; }
        public string email { get; set; }
        public string contactNo { get; set; }
        public string course { get; set; }
        public string branch { get; set; }
        public Nullable<int> semester { get; set; }
        public string college { get; set; }
        public Nullable<System.DateTime> regsdate { get; set; }
    }
}
